//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uploadfilePDFService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FDA_DROPBOXEntities : DbContext
    {
        public FDA_DROPBOXEntities()
            : base("name=FDA_DROPBOXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_fileinfo> tbl_fileinfo { get; set; }
        public virtual DbSet<tbl_info> tbl_info { get; set; }
        public virtual DbSet<tbl_log_history> tbl_log_history { get; set; }
        public virtual DbSet<tbl_staff_comment> tbl_staff_comment { get; set; }
    }
}
