//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uploadfilePDFService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_staff_comment
    {
        public int id { get; set; }
        public Nullable<int> tr_id { get; set; }
        public string staff_citizen { get; set; }
        public string staff_remark { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    }
}
