//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uploadfilePDFService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fileinfo
    {
        public int file_id { get; set; }
        public string file_name { get; set; }
        public Nullable<int> tr_id { get; set; }
        public string file_description { get; set; }
        public string path { get; set; }
        public string remark { get; set; }
        public string remark_status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    }
}
